### ISSUE TITLE
Support for AndroidX Orchestrator

### ISSUE THREAD

**Issue by b-demuth** [trevjonez/composer-gradle-plugin#35] opened 2019-01-09 15:15 UTC
Hi there, we've recently applied the AndroidX refactoring to our project but ran into issues when running our instrumentation tests via this plugin. The problem seems to be that the test orchestrator class and package names differ for Androidx, see the [AndroidJUnitRunner documentation](https://developer.android.com/training/testing/junit-runner). Would it be possible to support the new test orchestrator in addition to the old one?

**Comment by trevjonez** [comment] 2019-01-09 16:19
is this a possible duplicate of https://github.com/gojuno/composer/issues/158 ? 

This plugin doesn't know anything specifically about orchestrator so I am thinking the solution will lie in the main composer package.

**Comment by b-demuth** [comment] 2019-01-10 12:06
I don't think these two are related. You are right in that composer first would have to support the androidx way of starting the orchestrator, but this plugin would probably have to tell composer that androidx is used (or composer would have to auto-detect this). Alternatively, composer could provide a generic way to hand in a command prefix which is inserted before the "am instrument" part of the command line.

**Comment by trevjonez** [comment] 2019-02-12 16:12
upstream support seems to be incoming. https://github.com/gojuno/composer/pull/167

**Comment by Fondesa** [comment] 2019-03-26 10:29
Now the AndroidX orchestrator is supported by the version `0.6.0` of `Composer`.
https://github.com/gojuno/composer/pull/167

@b-demuth Until this Gradle plugin won't be updated to support the latest `Composer` version you can support it manually:

```
dependencies {
    composer "com.gojuno.composer:composer:0.6.0"
}

composer {
    // Since the latest version of Composer requires the explicit boolean for this argument, you should add it explicitely without using 'withOrchestrator'.
    instrumentationArgument("--with-orchestrator", "true")
}
```

**Closed as completed** 2019-03-29 02:12 UTC
Labels: Blocked

**Comment by trevjonez** [comment] 2019-03-29 03:09
planned for 0.11 hopefully tonight.
