### ISSUE TITLE
Tasks not showing in task list

### ISSUE THREAD

**Issue by tir38** [trevjonez/composer-gradle-plugin#37] opened 2019-01-28 18:24 UTC
I added composer gradle plugin as described in README. I then went to check that task was added:

`./gradlew app:tasks --all | grep -i composer`

But got zero results. After triple checking my setup I decided to just run the task `/gradlew app:testDebugCompose` and everything worked fine. The tests started up right away. I'm not sure why the composer task(s) didn't get add to the all tasks list

**Comment by trevjonez** [comment] 2019-01-28 18:33
that is a really great question, let me try and reproduce on my end. Thinking maybe it is due to the new lazy task api's but I need to look closer to be sure.

**Comment by trevjonez** [comment] 2019-03-29 03:12
Looks like I was missing a group attribute on the registered tasks which causes it to not be listed. fix will be in 0.11

**Closed as completed by trevjonez** 2019-03-29 03:12 UTC

**Comment by tir38** [comment] 2019-04-26 03:25
I was finally able to test this on 0.11 Looks good thanks.
